routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Login */
Route::get('/home', 'HomeController@index')->name('home');
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

/* Resources */
Route::resource('posts',         'PostController');
Route::resource('artists',       'ArtistController');
Route::resource('organizations', 'OrganizationController');
Route::resource('photos',        'PhotoController');
Route::resource('rooms',         'RoomController');
Route::resource('socials',       'SocialController');
Route::resource('styles',        'StyleController');
Route::resource('timetables',    'TimetableController');

app/Artist.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;

class Artist extends Model
{

    protected $fillable = ['organization_id', 'info_id'];

    public function styles() {
        return $this->belongsToMany( Style::class );
    }

    public function info() {
        return $this->belongsTo( Info::class );
    }

    public function organization() {
        return $this->belongsTo( Organization::class );
    }
    
    public function addStyle( Style $style ) {
        $this->styles()->save( $style );
    }

    public function hasStyle( Style $style ): bool {
        return $this->styles->contains( $style );
    }

    public function addStyles( Collection $styles ) {
        $this->styles()->saveMany( $styles->all() );
    }
}

app/Http/Controllers/ArtistController.php
<?php

namespace App\Http\Controllers;

use App\Artist;
use App\Info;
use App\Http\Requests\StoreArtistRequest;
use Illuminate\Support\Facades\Storage;

class ArtistController extends AuthenticatedController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('artists.index')->withArtists( Artist::all() );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreArtistRequest $request)
    {

        $validated = collect($request->validated());

        $artist = new Artist;

        $info = Info::create( $validated->only('name', 'description')->all() );
        $organization = $request->getOrganization();
        
        $artist = Artist::create([
            'organization_id' => $organization->id,
            'info_id' => $info->id
        ]);

        $photos = $request->getPhotos();
        $styles = $request->getStyles();
        $socials = $request->getSocials();
        
        if( $photos->isNotEmpty() ){
            
            foreach( $photos as $photo ) {
                $path = Storage::putFile('artists', $photo->url);
                $photo->url = $path;
            }

            $artist->info->addPhotos( $photos );
        }

        if( $styles->isNotEmpty() )
            $artist->addStyles( $styles );

        if( $socials->isNotEmpty() )
            $artist->info->addSocials( $socials );

        
        return redirect( route('artists.show', [ $artist->id ]) );

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Artist  $artist
     * @return \Illuminate\Http\Response
     */
    public function show(Artist $artist)
    {
        //
        return view('artists.show', compact('artist'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Artist  $artist
     * @return \Illuminate\Http\Response
     */
    public function edit(Artist $artist)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Artist  $artist
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Artist $artist)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Artist  $artist
     * @return \Illuminate\Http\Response
     */
    public function destroy(Artist $artist)
    {
        //
    }
}

resources/views/artists/bloclist.blade.php
<div class="card" style="width: 18rem;">

    @if( $artist->info->photos->isNotEmpty() )
        <div 
            class="custom-card-img-bg" 
            style="background-image:url({{ Storage::url( $artist->info->photos->first()->url ) }})">
        </div>
    @endif

    <div class="card-body">
        <h5 class="card-title"> {{ $artist->info->name }} </h5>
        <p class="card-text"> {{ $artist->info->description }} </p>
        <a href="{{ route('artists.show', $artist->id) }}" class="btn btn-primary"> See artist </a>
    </div>

</div>

resources/views/artists/index.blade.php
@extends('layouts.app')

@section('content')
    
    <section class="list artist-list">
        <div class="row p-3">
            
            @foreach ($artists as $artist)

            <div class="col-sm-4 mb-3"> @include('artists.bloclist') </div>

            @endforeach

        </div>
    </section>

    <section class="add add-artist">
        <h2> Add artist </h2>
        <form method="POST" action={{ route('artists.store') }} enctype="multipart/form-data">
            @csrf

            <div class="form-group">
                <label for="name" class="form-check-label"> Artist name </label>
                <input type="text" name="name" placeholder="Artist name" class="form-control" >
            </div>
            <div class="form-group">
                <label for="description" class="form-check-label"> Artist description </label>
                <textarea name="description" placeholder="Artist description..." class="form-control" ></textarea>
            </div>
            <div>
                <label> Artist styles </label>
                <div class="b-container">
                    @foreach (App\Style::all() as $style)
                        <div class="form-check">
                            <label for="styles" class="form-check-label "> 
                                <input type="checkbox" name="styles[]" value="{{ $style->id }}" class="form-check-input" >   
                                {{ $style->label }}
                            </label>
                        </div>
                    @endforeach
                </div>
            </div>
            <div>
                <label> Artist organization </label>
                <div class="b-container">
                    @foreach (App\Organization::all() as $organization)
                        <div class="form-check">
                            <label for="organization" class="form-check-label "> 
                                <input type="radio" name="organization" value="{{ $organization->id }}" class="form-check-input" >   
                                {{ $organization->info->name }}
                            </label>
                        </div>
                    @endforeach
                </div>
            </div>
            <div id="form-pictures" class="form-group">
                <label for="pictures" class="form-check-label"> Pictures </label>
                <div class="pictures-container b-container">
                    <input type="file" name="pictures[]" class="form-control-file" >
                </div>
                <button id="add-picture" class="btn btn-success"> <i class="fas fa-plus"></i> Add picture </button>
            </div>
            <div id="form-socials"  class="form-group">
                <label class="form-check-label"> Socials </label>
                <div class="socials-container b-container">
                    <input type="text" name="social_labels[]" placeholder="label: Artist soundcloud..." class="form-control" >
                    <input type="text" name="social_urls[]" placeholder="url: http://..." class="form-control" >
                    @foreach (App\SocialIcon::all() as $icon)
                        <div class="form-check">
                            <label for="icon" class="form-check-label">
                                <input type="radio" name="icon_0" value="{{ $icon->id }}" class="form-check-input" >   
                                <img src="{{ asset('icons/'.$icon->url) }}">
                            </label>
                        </div>
                    @endforeach
                </div>
                <button id="add-social" class="btn btn-success"> <i class="fas fa-plus"></i> Add social </button>
            </div>

            <input type="submit" value="Add artist" class="btn btn-primary">
        </form>
    </section>

@endsection

resources/views/artists/show.blade.php
@extends('layouts.app')

@section('content')

    <section id="artist">

        <h1> {{ $artist->info->name }} </h1>

        <img width="300px" src="{{ Storage::url( $artist->info->photos->first()->url ) }}" />

        <p> {{ $artist->info->description }} </p>
        
        <h2> Styles: </h2>
        @foreach (App\Style::all() as $style)
            <div class="form-check">
                <label for="styles" class="form-check-label "> 
                    <input 
                        type="checkbox"
                        name="styles[]" 
                        value="{{ $style->id }}" 
                        class="form-check-input"
                        @if( $artist->hasStyle( $style ) ) checked="true" @endif
                        >   
                    {{ $style->label }}
                </label>
            </div>
        @endforeach

        
    </section>

@endsection